### ISSUE TITLE
How do I show metrics for multiple applications separated by application context root or name

### ISSUE THREAD

**Issue by dbnex14** [eclipse/microprofile-config#726] opened 2021-11-01 23:33 UTC
If I have 10 applications running on same server (Liberty), how do I show /metrics and /health point by the application

Instead of this endpoint showing metrics for all 10 apps
`https://myserver/metrics`

I would like to have app context root in the endpoint so I can distinguish btw these 10 apps like:
```
https://myserver/app1/metrics
https://myserver/app2/metrics
https://myserver/app3/metrics
...
https://myserver/app10/metrics
```

**Comment by Emily-Jiang** [comment] 2021-11-02 09:41
@dbnex14 this is the not the repo for MicroProfile Config. You bug is related to Open Liberty. Please raise an issue at https://github.com/OpenLiberty/open-liberty/issues.

**Comment by dbnex14** [comment] 2021-11-02 15:54
> 
> 
> @dbnex14 this is the not the repo for MicroProfile Config. By the way, your issue is related to MicroProfile Metrics and Health. These specs does not provide a way to distinguish the endpoint per application. The best practices is not to deploy more than one app per server. You bug is related to Open Liberty. Please raise an issue at https://github.com/OpenLiberty/open-liberty/issues to have this discussed.

I do not understand what OpenLiberty has to do with this?  This is Micropfofile issue.  Besides, your documentation states this but it is very unclear how to set this to work.  I am refering to section 3.4 in this document https://download.eclipse.org/microprofile/microprofile-metrics-2.3/microprofile-metrics-spec-2.3.html#app-servers

The section should provide clear guidance and show example rather than write an essay about it.  

It also makes no sense to deploy only one app per server.  Deploying multiple apps to a single server is a common practice in industry.  As it is now, Microprofile has no use to us because of this which smells like a flaw in design.  Springboot gives this by default with actuators which include app context path by default in the metrics, health etc endpoints.

**Comment by Emily-Jiang** [comment] 2021-11-02 17:59
> > @dbnex14 this is the not the repo for MicroProfile Config. By the way, your issue is related to MicroProfile Metrics and Health. These specs does not provide a way to distinguish the endpoint per application. The best practices is not to deploy more than one app per server. You bug is related to Open Liberty. Please raise an issue at https://github.com/OpenLiberty/open-liberty/issues to have this discussed.
> 
> I do not understand what OpenLiberty has to do with this? This is Micropfofile issue. Besides, your documentation states this but it is very unclear how to set this to work. I am refering to section 3.4 in this document https://download.eclipse.org/microprofile/microprofile-metrics-2.3/microprofile-metrics-spec-2.3.html#app-servers
> 
> The section should provide clear guidance and show example rather than write an essay about it.
> 
I meant the Metrics spec does not define a behaviour. Some impl might consider to support what you proposed.
> It also makes no sense to deploy only one app per server. Deploying multiple apps to a single server is a common practice in industry. As it is now, Microprofile has no use to us because of this which smells like a flaw in design. Springboot gives this by default with actuators which include app context path by default in the metrics, health etc endpoints.
I was going to suggest you to open an issue on MicroProfile Metrics repo if you think the spec is unclear. I saw you have done so. Close this one.

**Closed by Emily-Jiang** 2021-11-02 17:59 UTC
Labels: bug :beetle:

**Comment by radcortez** [comment] 2021-11-03 11:51
Hi @dbnex14,

Thank you for reporting this.

I think this is more a Metrics issue than configuration. While these may be configured, the MP Config Spec has no knowledge about Metrics. It's the other way around. Metrics use Config so I believe the issue is more suited to the MP Metrics specification: https://github.com/eclipse/microprofile-metrics.

Do you mind reporting it there? Thanks!
