### ISSUE TITLE
Upgrade Eclipse MicroProfile with Jakarta EE 9

### ISSUE THREAD

**Issue by otaviojava** [eclipse/microprofile-config#668] opened 2021-01-07 16:33 UTC
Hello everyone, is there any roadmap to Eclipse MicroProfile that supports Jakarta EE 9?

The Working Group brings a new perspective to Jakarta EE specs such as JPA, NoSQL, JMS, etc.

It will be great to either standardize or define good practices to create complex objects from Eclipse MIcroProfile Config, such as an EntityManager or a NoSQL database connection.

**Comment by ederks85** [comment] 2021-01-07 17:51
Hi Otávio,

This is one of the topics I will bring up for discussion as soon as
possible with the steering committee. A few work items have been defined,
like creating a document where we will collect roadmap items, actions, and
future plans for MicroProfile. We discussed this on the last Hangout, you
can watch this part in the recording if you like.

Edwin

**Comment by keilw** [comment] 2021-01-10 18:32
@ederks85/all,

Based on the discussions in https://www.eclipse.org/lists/cn4j-alliance/msg00001.html there are several barriors for any MP API like Config to ever be consumed by Jakarta EE even in an implementation (and I am not convinced a Jakarta Spec or API would even need them anyway) bu this highlights the biggest problem aside from a **maturity level** and the general question of **namespace** (again implementations have very little problem to consume the same top level package they also got in many cases)

**Comment by brunobat** [comment] 2021-03-02 12:31
I am totally against this. 
MicroProfile should only change to Jakarta EE 10 and in the case that release has meaningful features. 
Updating all the namespaces will be a big overhead to whoever is using MicroProfile.
I can tell you I won't commit resources to this until I know what's in for Jakarta EE 10. I don't want to be in a position where I need to revert my services to use something else in order not to be stuck in a potential dead end.

**Comment by keilw** [comment] 2021-03-02 12:36
Then MP is dead at least for Jakarta EE, but so far you haven't even made it to Jakarta EE 9 while the first implementations already exist for Jakarta 9 but not a single vendor has implemented or applied MP 4 yet.
It is becoming the break block.

**Comment by radcortez** [comment] 2021-03-02 12:57
> Then MP is dead at least for Jakarta EE (even on an implementation level), but so far you haven't even made it to Jakarta EE 9 while the first implementations already exist for Jakarta 9 but not a single vendor has implemented or applied MP 4 yet.
> This way it is becoming the break block and legacy instead of an innovator.

This is incorrect. 

Wildfly just released a Beta last week with full support for MP 4.0:
https://twitter.com/bestansberry/status/1364935448464867328?s=20

Both Liberty and Quarkus are on their way to support it as well:
https://github.com/OpenLiberty/open-liberty/issues/11014
https://github.com/quarkusio/quarkus/issues/10522

The community is discussing if, when and how a move to Jakarta:
https://docs.google.com/document/d/1lOTdSvtH1eQA7Saa4WIwJeM_Z7-o0KSOXgK5K7bSoII/edit#heading=h.b987tdxsm6bk

**Comment by keilw** [comment] 2021-03-02 13:00
It's still a Beta and the problem is, MP 4.0 already trails behind Jakarta EE 9 so while that Beta of Wildfly may also apply MP4 it does for Jakarta EE 9 which is ahead of MP.

**Comment by radcortez** [comment] 2021-03-02 13:10
MP 4 targets Jakarta 8, because there was no Jakarta 9 available when MP 4 work started, so I think we cannot expect to expect something different. Discussions are taken place on how to move forward in these topics on the document that I've linked (which you also participated), so you know we are trying to come up with a solution.

Wildfly is planning the final release with the MP 4 support in the next few days. In Quarkus, we already have everything implemented, but we are postponing the release to align with some other work.

**Comment by keilw** [comment] 2021-03-02 13:15
As long as they work in their own isolated bubbles that might be fine, but if a true synergy was ever intended, the only way any Jakarta implementation could rely on a MP feature like config is, if those base features evolved faster and were independently available before the whole MP stack which it dosn't at the moment.

**Comment by radcortez** [comment] 2021-03-02 13:20
Config (or any other MP spec) can release independently. That was never an issue.

**Comment by radcortez** [comment] 2021-03-02 15:04
Thanks @Emily-Jiang. I remember seeing the blog, but I couldn't find it, so I've pointed to Liberty GH issue :)

**Comment by Emily-Jiang** [comment] 2021-03-02 16:09
@otaviojava thanks for raising this issue! As explained earlier, we will solve the alignment from MP community rather than handled by any individual spec to define. In light of this, I am going to close this issue and contine our converstation on the google mailing list and live hangouts.

**Comment by keilw** [comment] 2021-03-02 17:07
@Emily-Jiang it's not useful to ignore a special need and timeline of a few "reusable" specs like config because that does not make them useful, is there a proper place in the mailing list or Google Doc that even mentions this need or is it ignored?

**Comment by Emily-Jiang** [comment] 2021-03-02 17:26
@keilw I suggest is to move up the discussion to the google mailinglist and solve the whole thing instead of starting sub conversations. In my [previous](https://github.com/eclipse/microprofile-config/issues/668#issuecomment-788959372) comment, I have added a link to the googlegroup conversation. If you think a new need is to be expressed, it is best to bring to the overall mailinglist. This very topic is the current focus of MP community, which is why we need to meet up weekly for the time being.

**Comment by Emily-Jiang** [comment] 2021-04-26 10:46
Reopen this for some experiment since the plan of Jakarta EE 9 alignment was discussed and settled in the wide MP community.

**Comment by keilw** [comment] 2021-04-26 15:41
Glad to hear, at least for the standalone Jakarta NoSQL @otaviojava will be equally happy to see that because if made available in a timely manner for EE 9.x we could progress there, but for Jakarta EE 10 or above this is no an alternative to Jakarta Config ;-)

**Closed** 2021-06-02 15:41 UTC
Labels: use case :bulb:
